version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis-anti-bruteforce
    restart: unless-stopped
    # ports:
    #   - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-anti-bruteforce
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8888:8080"
    environment:
      - REDIS_ADDR=redis:6379

volumes:
  redis_data:
